name: Release on Tag
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      - name: Build
        run: zip -r build.xpi direct.js icons LICENSE manifest.json
      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: ' {a50d61ca-d27b-437a-8b52-5fd801a0a88b} '
          xpi: build.xpi
          manifest: manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
